// AUTO-GENERATED by scripts/export-data.ts
// Do not edit by hand. Regenerate via `npm run export`.
// Exported: 2026-04-23T18:24:58.922Z
// Source: Supabase project https://xyufrjjbhqndxfxbxcut.supabase.co

export const profileData = {
  name: "Asad Saeed",
  designation: "Senior Frontend Developer | React Js | Next Js | MERN Stack",
  residence: "Lahore, Punjab",
  nationality: "Pakistani",
  city: "Lahore",
  age: "26",
  email: "asadsaeed.dev@gmail.com",
  phone: "+92 3017631644 / +92 478730644",
  github_url: "https://github.com/Asad-Saeed",
  linkedin_url: "https://www.linkedin.com/in/asad-saeed-dev/",
  upwork_url: "https://www.upwork.com/freelancers/~01c9dc528b3e2edcde",
  profile_image_url:
    "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/profile/1775886906895-5qmrw6jvorb.png",
  resume_url:
    "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/documents/1775244061835-3xykg6hij9h.pdf",
  banner_image_url:
    "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/profile/background.png",
  banner_heading: "Hello, Check This Out!",
  banner_subheadings: ["Senior Frontend Developer", "MERN Stack Developer"],
  completed_projects_count: "27+",
  freelance_clients_count: "3+",
  honors_count: "4+",
  footer_text: "Made with ❤️ by Asad Saeed",
  copyright_year: "2026",
  slug: "asad-saeed",
  skills_banner_heading: "What Skills I Have!",
  background_banner_heading: "My Background",
  portfolio_banner_heading: "My Portfolio",
  contact_banner_heading: "Get In Touch",
  banner_emoji_url:
    "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/profile/emoji.png",
  explore_button_text: "Explore",
  explore_button_url: "https://www.upwork.com/freelancers/~01c9dc528b3e2edcde",
  show_github_section: true,
  github_section_heading: "GitHub Activity",
  show_expertise_section: true,
  show_recommendations_section: true,
  show_reviews_section: true,
  availability_status: "open_to_work",
  show_certifications_section: true,
  secondary_github_url: "https://github.com/Asad-gsoft-consulting",
} as const;

export const educationData = [
  {
    title: "Government College University Faisalabad",
    marks: "CGPA: 3.67/4.00",
    degree: "Bachelor Of Software Engineering",
    detail:
      "I earned my Bachelor of Software Engineering degree from Government College University Faisalabad, equipping myself with the knowledge and skills to thrive in the dynamic world of technology. Grateful for the transformative learning experience that prepared me for the professional realm.",
    year: "2018-2022",
    sort_order: 0,
  },
  {
    title: "The Educator College",
    marks: "Marks: 87%",
    degree: "Intermediate in Pre-Engineering",
    detail:
      "I pursued my Intermediate in Pre-Engineering at The Educator College, honing my skills for future endeavors in the field. Grateful for the academic opportunities that have shaped my educational path.",
    year: "2016-2018",
    sort_order: 1,
  },
  {
    title: "Govt High School and College",
    marks: "Marks: 82%",
    degree: "Matriculation (Computer Science)",
    detail:
      "I completed my matriculation from Govt High School and College, laying a strong foundation for my academic journey ahead. Grateful for the supportive environment that fostered my growth.",
    year: "2014-2016",
    sort_order: 2,
  },
] as const;

export const experienceData = [
  {
    title: "Global Software Consulting",
    role: "Senior Frontend Engineer",
    url: "https://www.gsoftconsulting.com/",
    description:
      "As a Senior Frontend Engineer, I specialize in developing high-quality, dynamic, and scalable web applications using React.js and Next.js. My responsibilities include crafting user-centric interfaces, optimizing application performance, and leading frontend development initiatives. Collaborating closely with cross-functional teams, I ensure the delivery of exceptional digital experiences.",
    year: "06/2023 - Present",
    location: "Lahore, Pakistan",
    sort_order: 0,
  },
  {
    title: "Arbitech Solution",
    role: "React Developer",
    url: "http://www.arbitechsolutions.org/",
    description:
      "At Arbitech Solution, I contributed as a React Developer, focusing on building modular, reusable components and ensuring seamless user experiences. My role involved designing and implementing responsive interfaces, troubleshooting performance issues, and collaborating with team members to meet project requirements within tight deadlines.",
    year: "11/2022 - 06/2023",
    location: "Lahore, Pakistan",
    sort_order: 1,
  },
  {
    title: "Game Train",
    role: "MERN Stack Intern",
    url: "https://www.gametrain.org/",
    description:
      "During my MERN stack development internship, I gained hands-on experience in building full-stack web applications. The program included learning advanced JavaScript, React.js, Node.js, and MongoDB concepts. My focus was on developing scalable backend services and interactive frontend interfaces, further solidifying my understanding of modern web development practices.",
    year: "08/2022 - 11/2022",
    location: "Lahore, Pakistan",
    sort_order: 2,
  },
  {
    title: "Convert Generation Information Technology (CGIT)",
    role: "WordPress Developer",
    url: "https://www.cgit.pk/",
    description:
      "As a WordPress Developer at CGIT, I designed and developed visually appealing, responsive websites tailored to client requirements. My responsibilities included customizing themes, enhancing frontend features, and maintaining website performance and security. I consistently delivered quality solutions that met and exceeded client expectations.",
    year: "10/2018 - 09/2020",
    location: "Faisalabad, Pakistan",
    sort_order: 3,
  },
] as const;

export const expertiseData = [
  {
    title: "Frontend Engineer",
    description:
      "I am a seasoned React and Next.js developer with 3+ years of experience in crafting seamless user interfaces and dynamic web applications. I specialize in building visually appealing, high-performance applications using React's component-based architecture and Next.js's server-side rendering capabilities. With a strong focus on API integration, I ensure efficient communication between frontend and backend systems. My commitment to code quality, performance optimization, and user-centered design drives the success of every project.",
    sort_order: 0,
  },
  {
    title: "Problem-Solving and Logic Building",
    description:
      "I excel at breaking down complex problems into manageable solutions through logical analysis and creative thinking. Whether debugging intricate issues, optimizing performance, or designing scalable systems, I approach challenges methodically to deliver effective and efficient results.",
    sort_order: 1,
  },
  {
    title: "Performance Optimization",
    description:
      "I have a strong focus on improving application performance by optimizing JavaScript, implementing lazy loading, code splitting, and analyzing bottlenecks to enhance user experiences and meet business goals.",
    sort_order: 2,
  },
  {
    title: "Cross-Browser Compatibility",
    description:
      "Ensuring web applications function consistently across various browsers and platforms is a core aspect of my expertise. I leverage techniques like progressive enhancement, feature detection, and thorough testing using tools like BrowserStack to deliver a seamless user experience, regardless of browser or device.",
    sort_order: 3,
  },
  {
    title: "Strong Communication Skills",
    description:
      "Effective communication is at the core of my collaboration with cross-functional teams, ensuring that project requirements are clearly understood, timelines are met, and expectations are managed efficiently.",
    sort_order: 4,
  },
  {
    title: "Leadership and Mentorship",
    description:
      "As a mentor to junior developers, I provide guidance on coding best practices, problem-solving strategies, and project management techniques to help them grow and excel in their careers.",
    sort_order: 5,
  },
  {
    title: "Continuous Learning",
    description:
      "I actively stay updated with the latest technologies and trends in web development, such as advancements in React, Next.js, TypeScript, and other frameworks, ensuring that my skills remain relevant and cutting-edge.",
    sort_order: 6,
  },
  {
    title: "Version Control",
    description:
      "Proficient in using Git, GitHub, and Bitbucket for effective collaboration and efficient code management, enabling smooth workflows in team-based projects.",
    sort_order: 7,
  },
  {
    title: "Scrum and Agile Methodologies",
    description:
      "Experienced in Agile methodologies, especially Scrum, using tools like Jira for task management, sprint planning, and progress tracking. I actively participate in stand-ups and retrospectives to ensure the delivery of high-quality software solutions.",
    sort_order: 8,
  },
  {
    title: "Open Source Contributor",
    description:
      "A passionate open-source contributor, I dedicate time to community-driven projects to learn best practices, share knowledge, and collaborate with like-minded developers. This allows me to stay updated with the latest trends and give back to the developer community.",
    sort_order: 9,
  },
] as const;

export const portfolioProjectsData = [
  {
    project_name: "Prism",
    url: "https://prism.creamyproducts.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/prism.png",
    project_detail:
      "A comprehensive goal management application that helps users set, track, and achieve their objectives effectively, with Stripe integration for seamless payment handling.",
    sort_order: 0,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "Next UI",
        sort_order: 1,
      },
      {
        tech_name: "Tailwind CSS",
        sort_order: 2,
      },
      {
        tech_name: "Stripe",
        sort_order: 3,
      },
      {
        tech_name: "Rest API",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "MNFT Swap",
    url: "https://6479defc346047008733d056--chipper-pastelito-5673e8.netlify.app/#/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/swap.png",
    project_detail:
      "A decentralized platform for minting and swapping NFTs, providing a seamless user experience for blockchain-based digital asset management.",
    sort_order: 1,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "SCSS",
        sort_order: 1,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 2,
      },
      {
        tech_name: "Ether.js",
        sort_order: 3,
      },
      {
        tech_name: "Block Chain",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "Safe Herit",
    url: "https://testing-safeherit.web.app/login",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/safeherit.png",
    project_detail:
      "A platform for safe and secure storage of digital assets and documents, with advanced security features and user-friendly interface.",
    sort_order: 2,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 1,
      },
      {
        tech_name: "Stripe",
        sort_order: 2,
      },
      {
        tech_name: "FireBase",
        sort_order: 3,
      },
      {
        tech_name: "Rest API",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "ESTRELLA TERA",
    url: "https://646f0f0bad16221200c6b558--silver-cuchufli-1d1850.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/estra.png",
    project_detail:
      "A blockchain platform for minting NFTs and managing token swaps with an intuitive interface and Ethereum support.",
    sort_order: 3,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "SCSS",
        sort_order: 1,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 2,
      },
      {
        tech_name: "Etherum",
        sort_order: 3,
      },
      {
        tech_name: "Block Chain",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "NR Mobiles & Accessories Company",
    url: "https://nrmobiles.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/nrmobiles.png",
    project_detail:
      "An e-commerce platform for mobile phones and accessories offering a user-friendly interface for product browsing and online shopping.",
    sort_order: 4,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next JS",
        sort_order: 0,
      },
      {
        tech_name: "Material UI",
        sort_order: 1,
      },
      {
        tech_name: "Strapi",
        sort_order: 2,
      },
      {
        tech_name: "GraphQL",
        sort_order: 3,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "Pedlar Store",
    url: "https://pedlar.store/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/pedlar.png",
    project_detail:
      "A modern e-commerce platform tailored for brands to showcase and sell their products online with a smooth user interface.",
    sort_order: 5,
    project_slug: "pedlar-store",
    challenge:
      "The client needed a modern, high-performance e-commerce platform that could handle their growing product catalog while delivering a seamless shopping experience. The existing solution suffered from slow page loads, clunky navigation, and a checkout flow that was causing significant cart abandonment.",
    solution:
      "Built a fully optimized e-commerce platform using Next.js with server-side rendering and static generation for product pages, delivering near-instant page loads. Implemented a streamlined product showcase with dynamic filtering, real-time search, and a frictionless multi-step checkout with integrated billing. Leveraged image optimization, code splitting, and edge caching to ensure consistent performance under high traffic.",
    impact:
      'Achieved sub-second page load times through SSR/SSG optimization. Streamlined the billing and checkout flow, reducing cart abandonment. Improved Core Web Vitals scores (LCP, CLS, FID) to Google\'s   "Good" threshold across all pages, boosting organic search visibility. ',
    role: "Senior Frontend Lead managing a team of 5 engineers. Owned the frontend architecture decisions, established coding standards and review processes, mentored junior developers, and personally built the   performance-critical checkout and billing modules. Coordinated with backend and design teams to deliver on tight deadlines.",
    technologies: [
      {
        tech_name: "ReactJS",
        sort_order: 0,
      },
      {
        tech_name: "REST API's",
        sort_order: 1,
      },
      {
        tech_name: "Material UI",
        sort_order: 2,
      },
      {
        tech_name: "JavaScript",
        sort_order: 3,
      },
      {
        tech_name: "Stripe",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "Company Needs",
    url: "https://company-needs-front-end.vercel.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/companyneeds.png",
    project_detail:
      "An e-commerce solution designed for businesses to manage product listings, inventory, and sales.",
    sort_order: 6,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next JS",
        sort_order: 0,
      },
      {
        tech_name: "SCSS",
        sort_order: 1,
      },
      {
        tech_name: "Strapi",
        sort_order: 2,
      },
      {
        tech_name: "GraphQL",
        sort_order: 3,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 4,
      },
    ],
  },
  {
    project_name: "FoodSwitch Cloud",
    url: "https://fscloud.foodswitch.com/login",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/fscloud.png",
    project_detail:
      "A data management system for food research institutions, enabling efficient handling and analysis of research data.",
    sort_order: 7,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next Js",
        sort_order: 0,
      },
      {
        tech_name: "Tailwind Css",
        sort_order: 1,
      },
      {
        tech_name: "Rest Api",
        sort_order: 2,
      },
      {
        tech_name: "Next Auth",
        sort_order: 3,
      },
    ],
  },
  {
    project_name: "Ask Cyborg",
    url: "https://askcyborg.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/askcyborg.png",
    project_detail:
      "An AI-powered chatbot platform designed to enhance customer support and provide instant query resolutions.",
    sort_order: 8,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next JS",
        sort_order: 0,
      },
      {
        tech_name: "PHP",
        sort_order: 1,
      },
      {
        tech_name: "REST API's",
        sort_order: 2,
      },
      {
        tech_name: "Material UI",
        sort_order: 3,
      },
    ],
  },
  {
    project_name: "Global Software Consulting",
    url: "https://www.gsoftconsulting.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/gsoft.png",
    project_detail:
      "A portfolio website showcasing Global Software Consulting's expertise and services in software development and IT consulting.",
    sort_order: 9,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "Material UI",
        sort_order: 1,
      },
      {
        tech_name: "Strapi",
        sort_order: 2,
      },
      {
        tech_name: "GraphQL",
        sort_order: 3,
      },
    ],
  },
  {
    project_name: "Digital Wave Solutions",
    url: "http://digitalwavesolutions.ca/",
    image_url: "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/dws.png",
    project_detail:
      "The portfolio of a digital marketing agency showcasing their services, expertise, and success stories.",
    sort_order: 10,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next JS",
        sort_order: 0,
      },
      {
        tech_name: "Material UI",
        sort_order: 1,
      },
      {
        tech_name: "Email Js",
        sort_order: 2,
      },
    ],
  },
  {
    project_name: "Obenan",
    url: "https://obenan.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/obenan.png",
    project_detail:
      "A digital marketing agency portfolio highlighting their AI-driven review systems and other marketing solutions.",
    sort_order: 11,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "Next JS",
        sort_order: 0,
      },
      {
        tech_name: "Material UI",
        sort_order: 1,
      },
      {
        tech_name: "Strapi",
        sort_order: 2,
      },
      {
        tech_name: "GraphQL",
        sort_order: 3,
      },
    ],
  },
  {
    project_name: "COINPICK 365",
    url: "https://644a86b90b7aea042688fb66--effulgent-torrone-565a9a.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/projects/coinpack.png",
    project_detail:
      "A crypto trading platform designed for secure and efficient cryptocurrency trading and portfolio management.",
    sort_order: 12,
    project_slug: "",
    challenge: "",
    solution: "",
    impact: "",
    role: "",
    technologies: [
      {
        tech_name: "React JS",
        sort_order: 0,
      },
      {
        tech_name: "SCSS",
        sort_order: 1,
      },
      {
        tech_name: "Bootstrap",
        sort_order: 2,
      },
      {
        tech_name: "Etherum",
        sort_order: 3,
      },
      {
        tech_name: "Block Chain",
        sort_order: 4,
      },
    ],
  },
] as const;

export const skillsData = [
  {
    tech_name: "React Js Engineer",
    url: "https://6479defc346047008733d056--chipper-pastelito-5673e8.netlify.app/#/",
    image_url: "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/react.png",
    description: "Expert in building interactive and dynamic web applications using React.",
    sort_order: 0,
    levels: [
      {
        title: "React Js",
        level: "95%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Next JS Engineer",
    url: "https://646f0f0bad16221200c6b558--silver-cuchufli-1d1850.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/nextjs.png",
    description: "Skilled in creating server-side rendered and static websites using Next.js.",
    sort_order: 1,
    levels: [
      {
        title: "Next JS",
        level: "95%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Javascript / Typescript Developer",
    url: "https://company-needs-front-end.vercel.app/",
    image_url: "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/jsts.png",
    description: "Proficient in developing robust and scalable applications using JS and TS.",
    sort_order: 2,
    levels: [
      {
        title: "Javascript / Typescript",
        level: "95%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "HTML, CSS Designer",
    url: "https://fscloud.foodswitch.com/login",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/htmlcss.png",
    description: "Experienced in creating responsive and visually appealing web layouts.",
    sort_order: 3,
    levels: [
      {
        title: "HTML, CSS",
        level: "95%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Frontend Framework Specialist",
    url: "https://askcyborg.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/bootstrap-vs-tailwindcss.png",
    description: "Expertise in modern CSS frameworks for rapid and responsive UI development.",
    sort_order: 4,
    levels: [
      {
        title: "Tailwind, Bootstrap, Module.css",
        level: "96%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "UI/UX Stylist",
    url: "https://www.gsoftconsulting.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/muisass.png",
    description: "Experienced in styling React applications with popular design libraries.",
    sort_order: 5,
    levels: [
      {
        title: "Next UI, Material UI, SCSS, Styled Components",
        level: "80%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "State Management Specialist",
    url: "http://digitalwavesolutions.ca/",
    image_url: "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/redux.jpg",
    description: "Proficient in state management using Context API and Redux Toolkit.",
    sort_order: 6,
    levels: [
      {
        title: "Context, Redux, Redux toolkit, Zustand",
        level: "90%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "API Integration Specialist",
    url: "https://nrmobiles.com/",
    image_url: "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/rest.png",
    description: "Skilled in integrating RESTful and GraphQL APIs for seamless data flow.",
    sort_order: 7,
    levels: [
      {
        title: "Rest and GraphQL Api's Integration",
        level: "90%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Version Control Expert",
    url: "https://obenan.com/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/Bitbucket-vs-Github.png",
    description: "Expert in version control for collaboration and efficient project management.",
    sort_order: 8,
    levels: [
      {
        title: "Git, GitHub, Bitbucket",
        level: "98%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Node Js, Express JS Developer",
    url: "https://644a86b90b7aea042688fb66--effulgent-torrone-565a9a.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/Node_Express.png",
    description: "Capable of building server-side applications using Node.js and Express.",
    sort_order: 9,
    levels: [
      {
        title: "Node Js, Express JS",
        level: "67%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Database Specialist",
    url: "https://644a86b90b7aea042688fb66--effulgent-torrone-565a9a.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/mongodb-vs-mysql.png",
    description: "Familiar with database management using MongoDB, FireBase and MySQL.",
    sort_order: 10,
    levels: [
      {
        title: "MongoDB, FireBase, MySql",
        level: "50%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "Backend Developer",
    url: "https://644a86b90b7aea042688fb66--effulgent-torrone-565a9a.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/backend.png",
    description:
      "Basic knowledge of backend development and server-side logic with Node Js and Express JS.",
    sort_order: 11,
    levels: [
      {
        title: "Node Js, Express JS",
        level: "67%",
        sort_order: 0,
      },
    ],
  },
  {
    tech_name: "WordPress Developer",
    url: "https://644a86b90b7aea042688fb66--effulgent-torrone-565a9a.netlify.app/",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/skills/wordpress.jpg",
    description: "Experienced in creating and customizing WordPress websites.",
    sort_order: 12,
    levels: [
      {
        title: "WordPress Developer",
        level: "80%",
        sort_order: 0,
      },
    ],
  },
] as const;

export const recommendationsData = [
  {
    name: "Athasham Shahzad",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/recommendations/ahtisham.jpeg",
    designation: "React Native | NEXT JS | Node | GraphQL",
    view: "Hello everyone! I'm excited to recommend Asad Saeed for any React.js opportunities. I've had the pleasure of collaborating with him on numerous projects, witnessing his profound grasp of React.js and Next.js concepts, consistently delivering top-notch code. Asad exhibits a strong commitment to learning and development, always eager to take on new challenges. With his reliability and dedication, he's a valuable addition to any React.js team. I highly endorse Asad Saeed! 👍! 🌟",
    linkedin_url: "https://www.linkedin.com/in/ahtishamshahzad/",
    sort_order: 0,
  },
  {
    name: "Raza Sabir",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/recommendations/raza.jpeg",
    designation: "React JS | NEXT JS | MUI | GraphQL",
    view: "I've had the honor of collaborating with Asad Saeed on several university projects, and I must emphasize his exceptional talent and strong work ethic. During our time together at Global Software Consulting, Asad Saeed's professionalism and meticulous attention to detail were evident, contributing significantly to our team's success. I confidently recommend Asad Saeed for any role that requires a highly skilled and committed individual.",
    linkedin_url: "https://www.linkedin.com/in/raza-mughal-developer/",
    sort_order: 1,
  },
  {
    name: "Muhammad Afzaal",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/recommendations/afzaal.jpeg",
    designation: "React Native | Javascript | typescript | ReactJs | Nextjs",
    view: "I enthusiastically endorse Asad Saeed as an accomplished React frontend developer with exceptional UI/UX design skills. His expertise in Node.js further amplifies his capacity to develop resilient and scalable applications. Asad Saeed's meticulous attention to detail, adept problem-solving abilities, and unwavering commitment to excellence make him an invaluable asset to any development team.",
    linkedin_url: "https://www.linkedin.com/in/muhammad-afzal-7333321b5/",
    sort_order: 2,
  },
  {
    name: "Mohsin Hussain",
    image_url:
      "https://xyufrjjbhqndxfxbxcut.supabase.co/storage/v1/object/public/recommendations/moshin.jpeg",
    designation: "React JS | Next.JS | Material UI | Graph QL | Cypress",
    view: "I strongly endorse Asad Saeed for web frontend development roles. Their proficiency in ReactJS and Next.js, along with their professionalism and unwavering dedication, render them an indispensable addition to any team.",
    linkedin_url: "https://www.linkedin.com/in/mohsin-hussain-24741916a/",
    sort_order: 3,
  },
] as const;

export const clientReviewsData = [
  {
    client_name: "Oliver Smith",
    client_location: "United Kingdom",
    client_source: "",
    client_review:
      "Working with Asad Saeed was a privilege; his deep understanding of web development and proficiency across frameworks were invaluable. I eagerly look forward to future collaborations.",
    sort_order: 0,
  },
  {
    client_name: "William Johnson",
    client_location: "Paris, France",
    client_source: "",
    client_review:
      "Collaborating with Asad Saeed was a game-changer; his expertise in web development and broad proficiency across frameworks were instrumental. I'm eager for the opportunity to work together again.",
    sort_order: 1,
  },
  {
    client_name: "Koshal",
    client_location: "India",
    client_source: "",
    client_review:
      "Asad Saeed's support and expertise in web app development were invaluable to our project success. His comprehensive understanding of various technologies ensured smooth progress throughout.",
    sort_order: 2,
  },
  {
    client_name: "Harry Wilson",
    client_location: "Amsterdam, Netherlands",
    client_source: "",
    client_review: "I anticipate future collaborations with great enthusiasm.",
    sort_order: 3,
  },
] as const;

export const certificationsData = [] as const;

export const languagesData = [
  {
    name: "English",
    proficiency: 96,
    sort_order: 0,
  },
  {
    name: "Urdu",
    proficiency: 100,
    sort_order: 1,
  },
] as const;

export const techStackData = [
  {
    name: "ReactJS",
    sort_order: 0,
  },
  {
    name: "NextJS",
    sort_order: 1,
  },
  {
    name: "JavaScript",
    sort_order: 2,
  },
  {
    name: "TypeScript",
    sort_order: 3,
  },
  {
    name: "CSS",
    sort_order: 4,
  },
  {
    name: "SCSS",
    sort_order: 5,
  },
  {
    name: "TailwindCSS",
    sort_order: 6,
  },
  {
    name: "Bootstrap",
    sort_order: 7,
  },
  {
    name: "Material UI",
    sort_order: 8,
  },
  {
    name: "Module.css",
    sort_order: 9,
  },
  {
    name: "Styled Components",
    sort_order: 10,
  },
  {
    name: "Redux",
    sort_order: 11,
  },
  {
    name: "Redux Toolkit",
    sort_order: 12,
  },
  {
    name: "GraphQL API",
    sort_order: 13,
  },
  {
    name: "Rest API",
    sort_order: 14,
  },
  {
    name: "Stripe Payment Integration",
    sort_order: 15,
  },
  {
    name: "Git",
    sort_order: 16,
  },
  {
    name: "GitHub",
    sort_order: 17,
  },
  {
    name: "Bitbucket",
    sort_order: 18,
  },
  {
    name: "Node Js",
    sort_order: 19,
  },
  {
    name: "Express JS",
    sort_order: 20,
  },
  {
    name: "MongoDB",
    sort_order: 21,
  },
  {
    name: "FireBase",
    sort_order: 22,
  },
  {
    name: "MySql",
    sort_order: 23,
  },
  {
    name: "Jira Software",
    sort_order: 24,
  },
  {
    name: "Postman",
    sort_order: 25,
  },
  {
    name: "Swagger",
    sort_order: 26,
  },
  {
    name: "Apollo Client",
    sort_order: 27,
  },
  {
    name: "Strapi",
    sort_order: 28,
  },
  {
    name: "Sanity",
    sort_order: 29,
  },
  {
    name: "Figma",
    sort_order: 30,
  },
  {
    name: "Adobe XD",
    sort_order: 31,
  },
] as const;

export const sidebarSkillsData = [
  {
    title: "React Js",
    level: "95%",
    sort_order: 0,
  },
  {
    title: "Next Js",
    level: "95%",
    sort_order: 1,
  },
  {
    title: "Javascript / Typescript",
    level: "95%",
    sort_order: 2,
  },
  {
    title: "HTML, CSS",
    level: "95%",
    sort_order: 3,
  },
  {
    title: "Tailwind, Bootstrap, Module.css",
    level: "96%",
    sort_order: 4,
  },
  {
    title: "Next UI, Material UI, SCSS, Styled Components",
    level: "80%",
    sort_order: 5,
  },
  {
    title: "Context, Redux, Redux toolkit",
    level: "90%",
    sort_order: 6,
  },
  {
    title: "Rest and GraphQL Api's Integration",
    level: "90%",
    sort_order: 7,
  },
  {
    title: "Git, GitHub, Bitbucket",
    level: "98%",
    sort_order: 8,
  },
  {
    title: "Node Js, Express JS",
    level: "67%",
    sort_order: 9,
  },
  {
    title: "MongoDB, FireBase, MySql",
    level: "50%",
    sort_order: 10,
  },
  {
    title: "Backend Developer",
    level: "50%",
    sort_order: 11,
  },
  {
    title: "WordPress Developer",
    level: "80%",
    sort_order: 12,
  },
] as const;
