ALTER TABLE profile
  ADD COLUMN IF NOT EXISTS show_expertise_section BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_recommendations_section BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_reviews_section BOOLEAN NOT NULL DEFAULT TRUE;
