ALTER TABLE portfolio_projects
  ADD COLUMN IF NOT EXISTS project_slug TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS challenge TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS solution TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS impact TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT '';
