-- ============================================================
-- 014_blog.sql — Blog posts + tags
-- Run AFTER 013_secondary_github.sql
-- DO NOT edit this file once deployed; append a new migration.
-- ============================================================

-- Posts table
CREATE TABLE IF NOT EXISTS posts (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title             TEXT NOT NULL DEFAULT '',
  slug              TEXT NOT NULL DEFAULT '',
  excerpt           TEXT NOT NULL DEFAULT '',
  content           TEXT NOT NULL DEFAULT '',
  cover_image_url   TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  reading_time      INTEGER NOT NULL DEFAULT 1,
  published_at      TIMESTAMPTZ,
  seo_title         TEXT NOT NULL DEFAULT '',
  seo_description   TEXT NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique slug per user (not globally unique so different users can share slugs, but
-- for a single-tenant setup add UNIQUE constraint for clean URLs)
ALTER TABLE posts ADD CONSTRAINT posts_slug_unique UNIQUE (slug);

-- Post tags junction (mirrors project_technologies pattern)
CREATE TABLE IF NOT EXISTS post_tags (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id   UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag       TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_posts_user_id_published_at ON posts(user_id, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);
CREATE INDEX IF NOT EXISTS idx_post_tags_post_id ON post_tags(post_id);

-- RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;

-- posts: anyone can read published posts only
CREATE POLICY "Public read published posts" ON posts
  FOR SELECT USING (status = 'published');

-- posts: owner can do everything (including read drafts)
CREATE POLICY "Owner manages own posts" ON posts
  FOR ALL USING (auth.uid() = user_id);

-- post_tags: public read (parent post RLS handles draft visibility)
CREATE POLICY "Public read post tags" ON post_tags
  FOR SELECT USING (true);

-- post_tags: authenticated users can manage tags (owner checked at application level)
CREATE POLICY "Authenticated manage post tags" ON post_tags
  FOR ALL USING (auth.role() = 'authenticated');

-- Add blog section toggle + metadata columns to profile
ALTER TABLE profile
  ADD COLUMN IF NOT EXISTS show_blog_section    BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS blog_eyebrow         TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS blog_heading         TEXT NOT NULL DEFAULT 'Latest Writing',
  ADD COLUMN IF NOT EXISTS blog_description     TEXT NOT NULL DEFAULT '';

-- Auto-update updated_at trigger for posts
CREATE OR REPLACE FUNCTION update_posts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER posts_updated_at_trigger
  BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_posts_updated_at();
